name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
<<<<<<< HEAD
          node-version: '20'
=======
          node-version: '22'
>>>>>>> 95c532a3444290818cf74f9b4f7c130a5221cbf3
      - run: npm ci
      - run: npx tsc --noEmit
      - run: npm test
